### ISSUE TITLE
Storing mp3 / wav / flac ?

### ISSUE THREAD

**Issue by daslicht** [molecuel/gridfs-uploader#1]
Hi,
is it possible to store mp3 / wav / flac files either?
Which type would that be , please?

**Comment by DominicBoettger** [comment]
You can save any file Type without limitations.

On Saturday, June 7, 2014, daslicht notifications@github.com wrote:

> Hi,
> is it possible to store mp3 / wav / flac files either?
> Which type would that be , please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DominicBoettger/gridfs-uploader/issues/1.

## 

Dominic Böttger

Dominic.Boettger@inspirationlabs.com

---

INSPIRATIONlabs GmbH

Rohrbacher Str. 79 | D-69115 Heidelberg | Germany
Tel. +49-6221-9853-680

inspirationlabs.com

Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim, HRB 704782
